const { app, BrowserWindow, ipcMain, shell, dialog } = require('electron');
const path = require('path');
const fs = require('fs-extra');
const { exec, spawn } = require('child_process');
const os = require('os');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 700,
    minWidth: 800,
    minHeight: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0f172a',
    icon: path.join(__dirname, 'assets', 'icon.png'),
  });

  mainWindow.loadFile('index.html');

  // Open external links in browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// IPC handlers for installer operations

// Check if Node.js is installed
ipcMain.handle('check-node', async () => {
  return new Promise((resolve) => {
    exec('node --version', (error, stdout) => {
      if (error) {
        resolve({ installed: false, version: null });
      } else {
        resolve({ installed: true, version: stdout.trim() });
      }
    });
  });
});

// Check if npm is installed
ipcMain.handle('check-npm', async () => {
  return new Promise((resolve) => {
    exec('npm --version', (error, stdout) => {
      if (error) {
        resolve({ installed: false, version: null });
      } else {
        resolve({ installed: true, version: stdout.trim() });
      }
    });
  });
});

// Check if git is installed
ipcMain.handle('check-git', async () => {
  return new Promise((resolve) => {
    exec('git --version', (error, stdout) => {
      if (error) {
        resolve({ installed: false, version: null });
      } else {
        resolve({ installed: true, version: stdout.trim() });
      }
    });
  });
});

// Select installation directory
ipcMain.handle('select-directory', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory', 'createDirectory'],
    title: 'Select Installation Directory',
    buttonLabel: 'Select Folder',
  });
  return result.canceled ? null : result.filePaths[0];
});

// Clone the repository
ipcMain.handle('clone-repo', async (event, { repoUrl, targetDir }) => {
  return new Promise((resolve, reject) => {
    const process = spawn('git', ['clone', repoUrl, targetDir]);

    let stdout = '';
    let stderr = '';

    process.stdout.on('data', (data) => {
      stdout += data.toString();
      event.sender.send('clone-progress', { type: 'stdout', data: data.toString() });
    });

    process.stderr.on('data', (data) => {
      stderr += data.toString();
      event.sender.send('clone-progress', { type: 'stderr', data: data.toString() });
    });

    process.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, stdout, stderr });
      } else {
        reject({ success: false, error: stderr || 'Clone failed', code });
      }
    });
  });
});

// Install npm dependencies
ipcMain.handle('npm-install', async (event, { targetDir }) => {
  return new Promise((resolve, reject) => {
    const process = spawn('npm', ['install'], {
      cwd: targetDir,
      shell: true,
    });

    let stdout = '';
    let stderr = '';

    process.stdout.on('data', (data) => {
      stdout += data.toString();
      event.sender.send('npm-progress', { type: 'stdout', data: data.toString() });
    });

    process.stderr.on('data', (data) => {
      stderr += data.toString();
      event.sender.send('npm-progress', { type: 'stderr', data: data.toString() });
    });

    process.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, stdout, stderr });
      } else {
        reject({ success: false, error: stderr || 'npm install failed', code });
      }
    });
  });
});

// Create environment file
ipcMain.handle('create-env-file', async (event, { targetDir, envConfig }) => {
  try {
    const envPath = path.join(targetDir, 'apps', 'web', '.env.local');

    let envContent = `# Generated by Tailored Solutions Installer\n\n`;

    for (const [key, value] of Object.entries(envConfig)) {
      if (value) {
        envContent += `${key}=${value}\n`;
      }
    }

    await fs.outputFile(envPath, envContent);
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// Update site content
ipcMain.handle('update-site-content', async (event, { targetDir, content }) => {
  try {
    const contentPath = path.join(targetDir, 'apps', 'web', 'data', 'site-content.json');
    await fs.writeJson(contentPath, content, { spaces: 2 });
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// Start development server
ipcMain.handle('start-dev-server', async (event, { targetDir }) => {
  return new Promise((resolve) => {
    const webDir = path.join(targetDir, 'apps', 'web');
    const process = spawn('npm', ['run', 'dev'], {
      cwd: webDir,
      shell: true,
    });

    process.stdout.on('data', (data) => {
      const output = data.toString();
      event.sender.send('dev-server-output', { type: 'stdout', data: output });

      // Check if server is ready
      if (output.includes('Ready') || output.includes('localhost:3000')) {
        resolve({ success: true, pid: process.pid });
      }
    });

    process.stderr.on('data', (data) => {
      event.sender.send('dev-server-output', { type: 'stderr', data: data.toString() });
    });

    // Resolve after timeout if not detected
    setTimeout(() => {
      resolve({ success: true, pid: process.pid });
    }, 10000);
  });
});

// Open URL in browser
ipcMain.handle('open-url', async (event, url) => {
  shell.openExternal(url);
  return { success: true };
});

// Get system info
ipcMain.handle('get-system-info', async () => {
  return {
    platform: process.platform,
    arch: process.arch,
    homedir: os.homedir(),
    tmpdir: os.tmpdir(),
  };
});
